name: Wallfair. Trading Engine

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DISABLE_SSL: true

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Setup
        run: |
          git config --global user.email "no-reploy@wallfair.io"
          git config --global user.name "Wallfair.io"
      - name: Prepare release
        run: npm run prepare-release
      - name: Push tags & changelog
        run: git push --follow-tags origin main
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
